/**
 * Config Generator Service
 *
 * Generates wrangler.toml and other configuration files
 * for the deployed CRM system
 */

import type { CloudflareResources } from '../types/deployment';

export class ConfigGenerator {
  /**
   * Generate wrangler.toml for the CRM Worker
   */
  generateWranglerConfig(projectName: string, resources: CloudflareResources): string {
    return `
name = "${projectName}-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "CONVERSATION_ROOM", class_name = "ConversationRoom" },
  { name = "USER_CONNECTION", class_name = "UserConnection" },
  { name = "MESSAGE_BROADCASTER", class_name = "MessageBroadcaster" },
  { name = "DELAYED_MESSAGE_PROCESSOR", class_name = "DelayedMessageProcessor" },
  { name = "DELAYED_MESSAGE_BUFFER", class_name = "DelayedMessageBuffer" },
  { name = "CUSTOMER_CONVERSATION_DO", class_name = "CustomerConversationDO" },
  { name = "CUSTOMER_MESSAGE_DO", class_name = "CustomerMessageDO" }
]

[[migrations]]
tag = "v1"
new_classes = [
  "ConversationRoom",
  "UserConnection",
  "MessageBroadcaster",
  "DelayedMessageProcessor",
  "DelayedMessageBuffer"
]

[[migrations]]
tag = "v2"
new_classes = ["CustomerConversationDO", "CustomerMessageDO"]

[[d1_databases]]
binding = "DB"
database_name = "${projectName}-db"
database_id = "${resources.d1DatabaseId}"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "${resources.kvSessionNamespaceId}"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "${resources.kvCacheNamespaceId}"

[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "${resources.r2BucketName}"

[[queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "${resources.queueName}"

[[queues.consumers]]
queue = "${resources.queueName}"
max_batch_size = 10
max_batch_timeout = 30

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "${this.generateSecret(32)}"
ENCRYPTION_KEY = "${this.generateSecret(32)}"

# Worker URL will be: https://${projectName}-worker.<account>.workers.dev
`.trim();
  }

  /**
   * Generate environment variables for frontend
   */
  generateFrontendEnv(workerUrl: string, pagesUrl: string): string {
    return `
VITE_API_BASE_URL=${workerUrl}
VITE_WS_BASE_URL=${workerUrl.replace('https://', 'wss://')}
VITE_APP_URL=${pagesUrl}
VITE_ENVIRONMENT=production
`.trim();
  }

  /**
   * Generate deployment summary
   */
  generateDeploymentSummary(
    projectName: string,
    resources: CloudflareResources,
    adminEmail: string
  ): string {
    return `
# CRM System Deployment Summary

## Project Information
- **Project Name:** ${projectName}
- **Deployment Date:** ${new Date().toISOString()}
- **Admin Email:** ${adminEmail}

## Deployed Resources

### Cloudflare Resources
- **D1 Database:** ${resources.d1DatabaseId}
- **KV Session Namespace:** ${resources.kvSessionNamespaceId}
- **KV Cache Namespace:** ${resources.kvCacheNamespaceId}
- **R2 Bucket:** ${resources.r2BucketName}
- **Queue:** ${resources.queueName}
- **Worker:** ${resources.workerId}
- **Pages Project:** ${resources.pagesProjectId}

### Application URLs
- **Frontend:** ${resources.pagesUrl}
- **Backend API:** ${resources.workerUrl}

## Next Steps

1. **Login to your CRM:**
   - URL: ${resources.pagesUrl}
   - Use the credentials sent to your email

2. **Change your password:**
   - Go to Settings → Account → Change Password
   - Use a strong, unique password

3. **Set up LINE OA integration:**
   - Go to Settings → Channels → LINE OA
   - Enter your LINE Channel credentials
   - Configure webhook URL

4. **Invite team members:**
   - Go to Team Management
   - Add members with their email addresses

## Support

If you encounter any issues:
- Email: support@yourcompany.com
- Documentation: https://docs.yourcompany.com
- Discord: https://discord.gg/yourcompany

---
Generated by CRM Web Installer v1.0.0
`.trim();
  }

  /**
   * Generate a random secret
   */
  private generateSecret(length: number): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
    let secret = '';
    const array = new Uint8Array(length);
    crypto.getRandomValues(array);

    for (let i = 0; i < length; i++) {
      secret += chars[array[i] % chars.length];
    }

    return secret;
  }

  /**
   * Generate random password for admin user
   */
  generateAdminPassword(): string {
    return this.generateSecret(16);
  }
}
