/**
 * Frontend Bundle Service
 *
 * Provides pre-built frontend assets for deployment to Cloudflare Pages
 * The bundle is generated from the main CRM frontend during build
 *
 * To generate the bundle, run: bun run build:frontend-bundle
 * from the main project root directory
 */

// Import the generated bundle (created by build:frontend-bundle script).
let GENERATED_ASSETS: Array<{
  path: string;
  content: string;
  contentType: string;
  originalSize: number;
}> | null = null;
let GENERATED_METADATA: { generatedAt: string; totalAssets: number } | null = null;

try {
  // Dynamic import to handle case when bundle hasn't been generated yet
  const bundle = await import('./generated/frontend-bundle.js');
  GENERATED_ASSETS = bundle.BUNDLED_FRONTEND_ASSETS;
  GENERATED_METADATA = bundle.BUNDLE_METADATA;
} catch {
  console.warn('[FrontendBundleService] Generated bundle not found. Deployment will be blocked until the bundle is built.');
}

export interface FrontendBundleConfig {
  apiBaseUrl: string;
  wsBaseUrl: string;
  appUrl: string;
  projectName: string;
}

export interface FrontendAsset {
  path: string;
  content: string;
  contentType: string;
}

export class FrontendBundleService {
  /**
   * Get all frontend assets for deployment
   *
   * Returns the pre-built frontend assets generated by build:frontend-bundle script.
   *
   * To generate the production bundle:
   * bun run build:frontend-bundle
   */
  getBundledAssets(config: FrontendBundleConfig): Map<string, string> {
    if (GENERATED_ASSETS && GENERATED_ASSETS.length > 0) {
      return this.getGeneratedAssets(config);
    }

    throw new Error('Generated frontend bundle not found. Run "bun run build:frontend-bundle" before deploying.');
  }

  /**
   * Get generated assets from the bundle
   */
  private getGeneratedAssets(config: FrontendBundleConfig): Map<string, string> {
    const assets = new Map<string, string>();

    if (!GENERATED_ASSETS) {
      throw new Error('Generated assets not available');
    }

    for (const asset of GENERATED_ASSETS) {
      if (asset.path === 'index.html') {
        // Inject runtime configuration into index.html
        const html = this.injectConfig(atob(asset.content), config);
        assets.set(asset.path, html);
      } else {
        // Decode base64 content
        assets.set(asset.path, atob(asset.content));
      }
    }

    // Add Cloudflare Pages config files
    assets.set('_headers', this.generateHeaders());
    assets.set('_redirects', this.generateRedirects());
    assets.set('config.json', JSON.stringify({
      apiBaseUrl: config.apiBaseUrl,
      wsBaseUrl: config.wsBaseUrl,
      appUrl: config.appUrl,
      projectName: config.projectName,
      version: '1.0.0'
    }, null, 2));

    return assets;
  }

  /**
   * Inject runtime configuration into index.html
   */
  private injectConfig(html: string, config: FrontendBundleConfig): string {
    const configScript = `<script>
    window.CRM_CONFIG = {
      apiBaseUrl: '${config.apiBaseUrl}',
      wsBaseUrl: '${config.wsBaseUrl}',
      appUrl: '${config.appUrl}',
      projectName: '${config.projectName}'
    };
  </script>`;

    return html.replace('</head>', `${configScript}</head>`);
  }

  /**
   * Check if a real bundle has been generated
   */
  hasGeneratedBundle(): boolean {
    return GENERATED_ASSETS !== null && GENERATED_ASSETS.length > 0;
  }

  /**
   * Get metadata about the generated bundle
   */
  getBundleMetadata(): { generatedAt: string; totalAssets: number } | null {
    return GENERATED_METADATA;
  }

  /**
   * Generate _headers file for Cloudflare Pages
   */
  private generateHeaders(): string {
    return `/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*.js
  Cache-Control: public, max-age=31536000, immutable

/*.css
  Cache-Control: public, max-age=31536000, immutable

/index.html
  Cache-Control: no-cache

/config.json
  Cache-Control: no-cache
`;
  }

  /**
   * Generate _redirects file for SPA routing
   */
  private generateRedirects(): string {
    return `/* /index.html 200`;
  }

  /**
   * Get content type for a file path
   */
  getContentType(path: string): string {
    const ext = path.split('.').pop()?.toLowerCase();
    const contentTypes: Record<string, string> = {
      'html': 'text/html',
      'css': 'text/css',
      'js': 'application/javascript',
      'json': 'application/json',
      'svg': 'image/svg+xml',
      'png': 'image/png',
      'jpg': 'image/jpeg',
      'jpeg': 'image/jpeg',
      'gif': 'image/gif',
      'ico': 'image/x-icon',
      'woff': 'font/woff',
      'woff2': 'font/woff2',
      'ttf': 'font/ttf',
      'eot': 'application/vnd.ms-fontobject'
    };
    return contentTypes[ext || ''] || 'application/octet-stream';
  }
}
