/**
 * Worker Bundle Service
 *
 * Provides pre-built, bundled Worker code for deployment
 * The bundle is generated from the main CRM project during build
 *
 * To generate the bundle, run: npm run build:worker-bundle
 * from the main project root directory
 */

import type { WorkerBinding } from '../types/cloudflare';
import type { CloudflareResources, DeploymentConfig } from '../types/deployment';
import { DURABLE_OBJECT_BINDINGS } from '../constants/durable-objects';

// Import the generated bundle (will be created by build:worker-bundle script)
// If the generated file doesn't exist, fallback to placeholder
let GENERATED_BUNDLE: string | null = null;
let GENERATED_METADATA: { generatedAt: string; originalSizeKB: number } | null = null;

try {
  // Dynamic import to handle case when bundle hasn't been generated yet
  const bundle = await import('./generated/worker-bundle.js');
  GENERATED_BUNDLE = bundle.BUNDLED_WORKER_SCRIPT;
  GENERATED_METADATA = bundle.BUNDLE_METADATA;
} catch {
  // Bundle not yet generated - will use placeholder
  console.warn('[WorkerBundleService] Generated bundle not found. Using placeholder.');
}

export interface WorkerBundleConfig {
  projectName: string;
  resources: CloudflareResources;
  config: DeploymentConfig;
  jwtSecret: string;
  encryptionKey: string;
}

export class WorkerBundleService {
  /**
   * Generate bindings for the Worker
   */
  generateBindings(resources: CloudflareResources, projectName: string): WorkerBinding[] {
    const bindings: WorkerBinding[] = [];

    // D1 Database binding
    if (resources.d1DatabaseId) {
      bindings.push({
        type: 'd1',
        name: 'DB',
        id: resources.d1DatabaseId
      });
    }

    // KV Session binding
    if (resources.kvSessionNamespaceId) {
      bindings.push({
        type: 'kv_namespace',
        name: 'SESSION_KV',
        namespace_id: resources.kvSessionNamespaceId
      });
    }

    // KV Cache binding
    if (resources.kvCacheNamespaceId) {
      bindings.push({
        type: 'kv_namespace',
        name: 'CACHE_KV',
        namespace_id: resources.kvCacheNamespaceId
      });
    }

    // R2 Bucket binding
    if (resources.r2BucketName) {
      bindings.push({
        type: 'r2_bucket',
        name: 'FILE_STORAGE',
        bucket_name: resources.r2BucketName
      });
    }

    // Queue binding
    if (resources.queueName) {
      bindings.push({
        type: 'queue',
        name: 'MESSAGE_QUEUE',
        queue_name: resources.queueName
      });
    }

    // Durable Object bindings — derived from shared constant (names must match wrangler.toml)
    for (const { name, class_name } of DURABLE_OBJECT_BINDINGS) {
      bindings.push({
        type: 'durable_object_namespace',
        name,
        class_name
        // No script_name — CF uses current script for self-referencing DO bindings
      });
    }

    return bindings;
  }

  /**
   * Generate environment variables for the Worker
   */
  generateEnvVars(config: WorkerBundleConfig): Record<string, string> {
    const env: Record<string, string> = {
      ENVIRONMENT: 'production',
      JWT_SECRET: config.jwtSecret,
      ENCRYPTION_KEY: config.encryptionKey
    };

    // Add LINE integration if configured
    if (config.config.lineChannelAccessToken) {
      env.LINE_CHANNEL_ACCESS_TOKEN = config.config.lineChannelAccessToken;
    }
    if (config.config.lineChannelSecret) {
      env.LINE_CHANNEL_SECRET = config.config.lineChannelSecret;
    }

    // Add Facebook integration if configured
    if (config.config.facebookPageAccessToken) {
      env.FACEBOOK_PAGE_ACCESS_TOKEN = config.config.facebookPageAccessToken;
    }
    if (config.config.facebookAppSecret) {
      env.FACEBOOK_APP_SECRET = config.config.facebookAppSecret;
    }

    return env;
  }

  /**
   * Get the bundled Worker script
   *
   * Returns the pre-built Worker bundle generated by build:worker-bundle script.
   * If the bundle hasn't been generated yet, returns a placeholder that provides
   * basic health check functionality.
   *
   * To generate the production bundle:
   * npm run build:worker-bundle
   */
  getBundledWorkerScript(): string {
    // Use generated bundle if available, otherwise fallback to placeholder
    if (GENERATED_BUNDLE) {
      return GENERATED_BUNDLE;
    }
    return BUNDLED_WORKER_SCRIPT;
  }

  /**
   * Check if a real bundle has been generated
   */
  hasGeneratedBundle(): boolean {
    return GENERATED_BUNDLE !== null;
  }

  /**
   * Get metadata about the generated bundle
   */
  getBundleMetadata(): { generatedAt: string; originalSizeKB: number } | null {
    return GENERATED_METADATA;
  }

  /**
   * Generate secrets for the Worker
   */
  generateSecrets(): { jwtSecret: string; encryptionKey: string } {
    return {
      jwtSecret: this.generateSecureSecret(64),
      encryptionKey: this.generateSecureSecret(64)
    };
  }

  /**
   * Generate a cryptographically secure secret
   */
  private generateSecureSecret(length: number): string {
    const array = new Uint8Array(length);
    crypto.getRandomValues(array);
    return Array.from(array)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');
  }
}

/**
 * Placeholder Worker Script (Fallback)
 *
 * This placeholder is used when the real Worker bundle hasn't been generated yet.
 * It provides basic functionality:
 * - Health check endpoint (/health, /api/system/health)
 * - Version endpoint (/api/version)
 * - CORS headers
 *
 * To generate the real bundle with full CRM functionality:
 * npm run build:worker-bundle
 *
 * The generated bundle will be automatically used when available.
 */
const BUNDLED_WORKER_SCRIPT = `
// CRM Worker Bundle - Placeholder
// This should be replaced with the actual bundled Worker code

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // CORS headers
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    };

    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    // Health check endpoint
    if (url.pathname === '/health' || url.pathname === '/api/system/health') {
      return new Response(JSON.stringify({
        success: true,
        status: 'healthy',
        timestamp: new Date().toISOString(),
        version: '1.0.0',
        environment: env.ENVIRONMENT || 'production'
      }), {
        headers: {
          'Content-Type': 'application/json',
          ...corsHeaders
        }
      });
    }

    // API version endpoint
    if (url.pathname === '/api/version') {
      return new Response(JSON.stringify({
        version: '1.0.0',
        name: 'CRM System',
        deployed: new Date().toISOString()
      }), {
        headers: {
          'Content-Type': 'application/json',
          ...corsHeaders
        }
      });
    }

    // TODO: Import and use the actual CRM Worker handlers
    // This placeholder should be replaced with:
    // import { app } from './src/index';
    // return app.fetch(request, env, ctx);

    return new Response(JSON.stringify({
      error: 'Worker bundle not yet configured',
      message: 'Please replace the placeholder with the actual CRM Worker bundle'
    }), {
      status: 503,
      headers: {
        'Content-Type': 'application/json',
        ...corsHeaders
      }
    });
  }
};
`;
