/**
 * File Management Error Codes
 * 檔案管理錯誤代碼定義
 */

// File validation errors
export const FILE_VALIDATION_ERRORS = {
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TOO_SMALL: 'FILE_TOO_SMALL',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_MIME_TYPE: 'INVALID_MIME_TYPE',
  INVALID_EXTENSION: 'INVALID_EXTENSION',
  PROHIBITED_FILE_TYPE: 'PROHIBITED_FILE_TYPE',
  MISSING_FILE: 'MISSING_FILE',
  CORRUPTED_FILE: 'CORRUPTED_FILE',
  INVALID_FILENAME: 'INVALID_FILENAME',
  FILENAME_TOO_LONG: 'FILENAME_TOO_LONG',
  INVALID_FILE_SIGNATURE: 'INVALID_FILE_SIGNATURE',
  VIRUS_DETECTED: 'VIRUS_DETECTED',
  MALICIOUS_CONTENT: 'MALICIOUS_CONTENT'
} as const;

// Upload errors
export const UPLOAD_ERRORS = {
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_TIMEOUT: 'UPLOAD_TIMEOUT',
  UPLOAD_INTERRUPTED: 'UPLOAD_INTERRUPTED',
  STORAGE_FULL: 'STORAGE_FULL',
  STORAGE_ERROR: 'STORAGE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  CONCURRENT_LIMIT_EXCEEDED: 'CONCURRENT_LIMIT_EXCEEDED',
  DUPLICATE_FILE: 'DUPLICATE_FILE',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
} as const;

// Download errors
export const DOWNLOAD_ERRORS = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_EXPIRED: 'FILE_EXPIRED',
  FILE_DELETED: 'FILE_DELETED',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_URL: 'INVALID_URL',
  URL_EXPIRED: 'URL_EXPIRED',
  BANDWIDTH_EXCEEDED: 'BANDWIDTH_EXCEEDED',
  DOWNLOAD_TIMEOUT: 'DOWNLOAD_TIMEOUT'
} as const;

// Processing errors
export const PROCESSING_ERRORS = {
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  THUMBNAIL_GENERATION_FAILED: 'THUMBNAIL_GENERATION_FAILED',
  COMPRESSION_FAILED: 'COMPRESSION_FAILED',
  METADATA_EXTRACTION_FAILED: 'METADATA_EXTRACTION_FAILED',
  FORMAT_CONVERSION_FAILED: 'FORMAT_CONVERSION_FAILED',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  PROCESSING_TIMEOUT: 'PROCESSING_TIMEOUT',
  INSUFFICIENT_RESOURCES: 'INSUFFICIENT_RESOURCES'
} as const;

// Storage errors
export const STORAGE_ERRORS = {
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  BUCKET_NOT_FOUND: 'BUCKET_NOT_FOUND',
  INSUFFICIENT_STORAGE: 'INSUFFICIENT_STORAGE',
  STORAGE_READ_ERROR: 'STORAGE_READ_ERROR',
  STORAGE_WRITE_ERROR: 'STORAGE_WRITE_ERROR',
  STORAGE_DELETE_ERROR: 'STORAGE_DELETE_ERROR',
  STORAGE_COPY_ERROR: 'STORAGE_COPY_ERROR',
  STORAGE_MOVE_ERROR: 'STORAGE_MOVE_ERROR',
  INVALID_STORAGE_KEY: 'INVALID_STORAGE_KEY',
  STORAGE_ACCESS_DENIED: 'STORAGE_ACCESS_DENIED'
} as const;

// Database errors
export const DATABASE_ERRORS = {
  DATABASE_ERROR: 'DATABASE_ERROR',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  FOREIGN_KEY_ERROR: 'FOREIGN_KEY_ERROR',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  QUERY_TIMEOUT: 'QUERY_TIMEOUT'
} as const;

// Authentication and authorization errors
export const AUTH_ERRORS = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_USER_CONTEXT: 'INVALID_USER_CONTEXT'
} as const;

// Configuration errors
export const CONFIG_ERRORS = {
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  MISSING_CONFIGURATION: 'MISSING_CONFIGURATION',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR'
} as const;

// All error codes combined
export const ERROR_CODES = {
  ...FILE_VALIDATION_ERRORS,
  ...UPLOAD_ERRORS,
  ...DOWNLOAD_ERRORS,
  ...PROCESSING_ERRORS,
  ...STORAGE_ERRORS,
  ...DATABASE_ERRORS,
  ...AUTH_ERRORS,
  ...CONFIG_ERRORS
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

// Error messages mapping
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  // File validation
  FILE_TOO_LARGE: '檔案大小超過限制',
  FILE_TOO_SMALL: '檔案大小過小',
  INVALID_FILE_TYPE: '不支援的檔案類型',
  INVALID_MIME_TYPE: '無效的檔案格式',
  INVALID_EXTENSION: '無效的檔案副檔名',
  PROHIBITED_FILE_TYPE: '禁止的檔案類型',
  MISSING_FILE: '缺少檔案',
  CORRUPTED_FILE: '檔案已損壞',
  INVALID_FILENAME: '無效的檔案名稱',
  FILENAME_TOO_LONG: '檔案名稱過長',
  INVALID_FILE_SIGNATURE: '檔案簽章無效',
  VIRUS_DETECTED: '偵測到病毒',
  MALICIOUS_CONTENT: '偵測到惡意內容',

  // Upload
  UPLOAD_FAILED: '檔案上傳失敗',
  UPLOAD_TIMEOUT: '上傳逾時',
  UPLOAD_INTERRUPTED: '上傳中斷',
  STORAGE_FULL: '儲存空間已滿',
  STORAGE_ERROR: '儲存錯誤',
  NETWORK_ERROR: '網路錯誤',
  QUOTA_EXCEEDED: '超過配額限制',
  CONCURRENT_LIMIT_EXCEEDED: '超過同時上傳限制',
  DUPLICATE_FILE: '檔案已存在',
  PERMISSION_DENIED: '權限不足',

  // Download
  FILE_NOT_FOUND: '檔案不存在',
  FILE_EXPIRED: '檔案已過期',
  FILE_DELETED: '檔案已刪除',
  DOWNLOAD_FAILED: '下載失敗',
  ACCESS_DENIED: '存取被拒絕',
  INVALID_URL: '無效的連結',
  URL_EXPIRED: '連結已過期',
  BANDWIDTH_EXCEEDED: '超過頻寬限制',
  DOWNLOAD_TIMEOUT: '下載逾時',

  // Processing
  PROCESSING_FAILED: '檔案處理失敗',
  THUMBNAIL_GENERATION_FAILED: '縮圖產生失敗',
  COMPRESSION_FAILED: '檔案壓縮失敗',
  METADATA_EXTRACTION_FAILED: '元數據提取失敗',
  FORMAT_CONVERSION_FAILED: '格式轉換失敗',
  UNSUPPORTED_FORMAT: '不支援的格式',
  PROCESSING_TIMEOUT: '處理逾時',
  INSUFFICIENT_RESOURCES: '資源不足',

  // Storage
  STORAGE_UNAVAILABLE: '儲存服務不可用',
  BUCKET_NOT_FOUND: '儲存桶不存在',
  INSUFFICIENT_STORAGE: '儲存空間不足',
  STORAGE_READ_ERROR: '讀取儲存失敗',
  STORAGE_WRITE_ERROR: '寫入儲存失敗',
  STORAGE_DELETE_ERROR: '刪除儲存失敗',
  STORAGE_COPY_ERROR: '複製儲存失敗',
  STORAGE_MOVE_ERROR: '移動儲存失敗',
  INVALID_STORAGE_KEY: '無效的儲存金鑰',
  STORAGE_ACCESS_DENIED: '儲存存取被拒絕',

  // Database
  DATABASE_ERROR: '資料庫錯誤',
  RECORD_NOT_FOUND: '記錄不存在',
  DUPLICATE_RECORD: '重複記錄',
  FOREIGN_KEY_ERROR: '外鍵錯誤',
  CONSTRAINT_VIOLATION: '約束違反',
  TRANSACTION_FAILED: '交易失敗',
  CONNECTION_ERROR: '連線錯誤',
  QUERY_TIMEOUT: '查詢逾時',

  // Auth
  UNAUTHORIZED: '未授權',
  FORBIDDEN: '禁止存取',
  TOKEN_EXPIRED: '令牌已過期',
  INVALID_TOKEN: '無效令牌',
  INSUFFICIENT_PERMISSIONS: '權限不足',
  USER_NOT_FOUND: '使用者不存在',
  INVALID_USER_CONTEXT: '無效的使用者上下文',

  // Config
  INVALID_CONFIGURATION: '無效的設定',
  MISSING_CONFIGURATION: '缺少設定',
  SERVICE_UNAVAILABLE: '服務不可用',
  FEATURE_DISABLED: '功能已停用',
  ENVIRONMENT_ERROR: '環境錯誤'
} as const;